const productos = [
    { id: "moyu-rs3m-2020", nombre: "MoYu RS3 M 2020", precio: 45000, categoria: "3x3", imagen: "img/rs3m-2020.webp", descripcion: "El rey de la gama de entrada económica. Magnético, ajustable y con una relación calidad-precio inigualable para romper récords." },
    { id: "gan-12-maglev", nombre: "GAN 12 MagLev UV", precio: 260000, categoria: "3x3", imagen: "img/GAN-12.webp", descripcion: "Tecnología de levitación magnética sin resortes, acabado exterior UV brillante y sistema de posicionamiento de núcleos avanzado." },
    { id: "qiyi-valk-3m", nombre: "QiYi Valk 3 M", precio: 95000, categoria: "3x3", imagen: "img/valk3m.webp", descripcion: "Un clásico de competición legendario rediseñado con imanes de fábrica. Giro sumamente suave y controlable." },
    { id: "moyu-wrm-v9", nombre: "MoYu Weilong WR M V9 Special", precio: 195000, categoria: "3x3", imagen: "img/wrm9.webp", descripcion: "Elección de múltiples campeones mundiales. Cuenta con ajuste de rebote y una velocidad impresionante." },
    { id: "gang-14-pro", nombre: "GAN 14 Pro MagLev", precio: 310000, categoria: "3x3", imagen: "img/GAN-14.webp", descripcion: "El tope de gama actual de GAN. Personalización milimétrica de tensiones y alineación magnética de última generación." },
    { id: "yj-mgc-3", nombre: "YJ MGC 3x3 v2", precio: 65000, categoria: "3x3", imagen: "img/mgcv2.webp", descripcion: "Imanes robustos y un rendimiento digno de alta competencia a un precio muy accesible." },
    { id: "tornado-v3-pioneer", nombre: "X-Man Tornado V3 M Pioneer", precio: 210000, categoria: "3x3", imagen: "img/tornadov3.webp", descripcion: "Uno de los cubos más populares del mundo por su corte de esquinas increíblemente flexible y magnetización de núcleo." },
    { id: "dayan-tengyun-v2", nombre: "DaYan TengYun V2 M", precio: 130000, categoria: "3x3", imagen: "img/dayantengyunm.webp", descripcion: "Famoso por ser el cubo más silencioso del mercado. Perfecto para practicar en cualquier lugar sin molestar a nadie." },
    { id: "rs3m-v5-bc", nombre: "MoYu RS3M V5 Ball-Core", precio: 115000, categoria: "3x3", imagen: "img/rs3mv5.webp", descripcion: "La evolución de la saga RS3M con tecnología Ball-Core y autoalineación magnética del núcleo." },
    { id: "qiyi-speed-3x3", nombre: "QiYi Warrior S 3x3", precio: 22000, categoria: "3x3", imagen: "img/qiyiwarrior.webp", descripcion: "Ideal para principiantes y colegios. Sin imanes, pero con un giro fluido y sin trabarse." },
    
    // Categoría 4x4
    { id: "moyu-mgc-4", nombre: "YJ MGC 4x4 Magnetic", precio: 95000, categoria: "4x4", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Considerado por muchos el mejor 4x4 calidad-precio del mundo. Estable y rápido." },
    { id: "gan-460-m", nombre: "GAN 460 M", precio: 190000, categoria: "4x4", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Ligero, con sistema de imanes visibles y esquinas optimizadas para evitar bloqueos." },
    { id: "aosu-wrm-4x4", nombre: "MoYu AoSu WR M 4x4", precio: 220000, categoria: "4x4", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "El preferido de la élite mundial para la prueba reina de cuatro capas." },
    { id: "qiyi-qIYuan-4x4", nombre: "QiYi Qiyuan S2 4x4", precio: 38000, categoria: "4x4", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Opción económica sin imanes para aprender la reducción de centros en 4x4." },
    { id: "vin-4x4", nombre: "Vin Cube 4x4", precio: 175000, categoria: "4x4", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Diseño compacto con excelente alineación de capas internas." },

    // Categoría 5x5
    { id: "moyu-mgc-5", nombre: "YJ MGC 5x5 Magnetic", precio: 120000, categoria: "5x5", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Giro mantecoso y tamaño ideal para manos grandes y pequeñas." },
    { id: "aosheng-wrm-5x5", nombre: "MoYu AoShi WR M 5x5", precio: 250000, categoria: "5x5", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Rendimiento profesional de alta gama con imanes perfectamente calibrados." },
    { id: "yuxin-little-magic-5", nombre: "YuXin Little Magic 5x5 M", precio: 85000, categoria: "5x5", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Sorprendentemente ligero y rápido para ser un 5x5 económico." },

    // Categoría Megaminx y Pyraminx
    { id: "gan-megaminx", nombre: "GAN Megaminx Magnetic", precio: 240000, categoria: "Megaminx", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Diseño ergonómico con crestas antideslizantes y posicionamiento magnético preciso." },
    { id: "moyu-megaminx-m", nombre: "MoYu Megaminx M", precio: 110000, categoria: "Megaminx", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Piezas cóncavas para un agarre excepcional durante solves largos." },
    { id: "qiyi-pyraminx-m", nombre: "QiYi Pyraminx M", precio: 45000, categoria: "Pyraminx", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "El pyraminx magnético más vendido del mundo. Imán de clicks muy satisfactorios." },
    { id: "gan-pyraminx", nombre: "GAN Pyraminx Enhanced", precio: 150000, categoria: "Pyraminx", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Imanes de núcleo avanzados y puntas con alineación magnética independiente." },
    { id: "qiyi-skewb-m", nombre: "QiYi Skewb M", precio: 50000, categoria: "Skewb", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Movimiento suave y rápido con sistema magnético de balines." },
    { id: "moyu-clock", nombre: "MoYu AoFu / QiYi Clock", precio: 95000, categoria: "Clock", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "El rompecabezas de esferas y ruedas con pines magnéticos ajustables." },

    // Lubricantes y Accesorios
    { id: "lube-dnm-37", nombre: "Lubricante GAN DNM-37", precio: 35000, categoria: "Lubricantes", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Lubricante a base de agua que otorga una velocidad explosiva instantánea a tus cubos." },
    { id: "lube-cuber-speed", nombre: "Lubricante Martian (Speed)", precio: 38000, categoria: "Lubricantes", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Equilibrio perfecto entre velocidad y control duradero." },
    { id: "lube-gravity", nombre: "Lubricante Gravity (Control)", precio: 38000, categoria: "Lubricantes", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Ideal para suavizar caras internas y aportar control en cubos muy rápidos." },
    { id: "mat-gan", nombre: "Matricula / Tapete GAN Oficial", precio: 65000, categoria: "Accesorios", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Tapete de neopreno con ganchos de conexión para timer profesional V2 y V3." },
    { id: "timer-smart-gan", nombre: "GAN Smart Timer", precio: 140000, categoria: "Accesorios", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Cronómetro con conexión Bluetooth para registrar tus tiempos automáticamente en la app móvil." },
    { id: "backpack-cube", nombre: "Maleta / Morral CubeCarrier", precio: 110000, categoria: "Accesorios", imagen: "https://images.unsplash.com/photo-1591991564664-9cb264b31745?auto=format&fit=crop&q=80&w=400", descripcion: "Espuma interna troquelada a la medida para llevar hasta 12 cubos seguros a torneos." },
    { id: "pyraminx yuxin", nombre: "Pyraminx Yuxin Little Magic M", precio: 50000, categoria: "Pyraminx", imagen: "", descripcion:"Conocido por ser el pyraminx que utilizan los mejores del mundo en esta categoria"}
];